// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkfT5uI-QW-3PNx1GHu506BOdl_Z2UR2k',
    appId: '1:373853454857:web:775db8465b05679c106ed8',
    messagingSenderId: '373853454857',
    projectId: 'storm-theiterators',
    authDomain: 'storm-theiterators.firebaseapp.com',
    storageBucket: 'storm-theiterators.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3N1F_uaKkDEVLvVPHhi8xHoW-k_Ab0xQ',
    appId: '1:373853454857:android:f1e35dba76138ac7106ed8',
    messagingSenderId: '373853454857',
    projectId: 'storm-theiterators',
    storageBucket: 'storm-theiterators.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACjLXt8ytSfeCkli3NhwSr00u1xKoDzHE',
    appId: '1:373853454857:ios:b683d93845dfe865106ed8',
    messagingSenderId: '373853454857',
    projectId: 'storm-theiterators',
    storageBucket: 'storm-theiterators.appspot.com',
    iosBundleId: 'com.example.nexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACjLXt8ytSfeCkli3NhwSr00u1xKoDzHE',
    appId: '1:373853454857:ios:13d5f3b833a8929c106ed8',
    messagingSenderId: '373853454857',
    projectId: 'storm-theiterators',
    storageBucket: 'storm-theiterators.appspot.com',
    iosBundleId: 'com.example.nexus.RunnerTests',
  );
}
